version: '2'
services:
    recipeapp-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        command: mongos --configdb recipeapp-mongodb-config
    recipeapp-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    recipeapp-mongodb-config:
        image: mongo:4.0.2
        container_name: recipeapp-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
